name: CI Pipeline

on:
  push:
    branches: [ main, master, dev, develop ]
  pull_request:
    branches: [ main, master, dev, develop ]

jobs:
  ci:
    name: Lint, Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Prisma Client Generation
        run: npx prisma generate

      - name: Run Linter
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test

      - name: Run Application Build
        run: npm run build
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/compusum_db?schema=public"
          NEXTAUTH_SECRET: "ci-secret-key-32-chars-long-test"
